### ISSUE TITLE
More Information on LLM usecase (proofs)

### ISSUE THREAD

**Issue by RawthiL** [StarkWizard/cairo-llm#21]
Hi, I just found your repo, and I'm new to StarkNet, I'm confused about the objective of this repository. I see that i contains code to finetune and quantize LLM models in traditional quantization schemes, but I'm having trouble understanding the connection with STARK profs.
You state:
"we aim to provide a robust and reliable LLM for all your Cairo smart contract needs."
does this mean that you are generating proofs of LLM execution? 

Thanks!

**Comment by pechaut78** [comment]
Hi Ramiro,

The goal is to make an assistant on the Staknet echosystem. There is already a Llama and Mistral fine tuned that can answer some questions about Cairo and generate some code

Cordialement,
CHAUT Pierre-Emmanuel
________________________________
De : Ramiro R. C. ***@***.***>
Envoyé : lundi 8 juillet 2024 21:46
À : StarkWizard/cairo-llm ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [StarkWizard/cairo-llm] More Information on LLM usecase (proofs) (Issue #21)


Hi, I just found your repo, and I'm new to StarkNet, I'm confused about the objective of this repository. I see that i contains code to finetune and quantize LLM models in traditional quantization schemes, but I'm having trouble understanding the connection with STARK profs.
You state:
"we aim to provide a robust and reliable LLM for all your Cairo smart contract needs."
does this mean that you are generating proofs of LLM execution?

Thanks!

**Comment by RawthiL** [comment]
Now I see, thanks for the clarification!
