### ISSUE TITLE
Requirements does not conform with Mac

### ISSUE THREAD

**Issue by fredsco** [StarkWizard/cairo-llm#7]
the requirements.txt for Mac seems to be the same for windows + it is referencing to CUDA and is generating the following error:

> Collecting auto-gptq (from -r requirements.txt (line 20))
  Using cached auto_gptq-0.6.0.tar.gz (120 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

> python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [7 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/private/var/folders/5_/zvd833w9089dv34xgl1rd99c0000gn/T/pip-install-7u1estdr/auto-gptq_8cb9ba55704d49f4b9cf198273d07dd3/setup.py", line 60, in <module>
>           CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
>                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       AttributeError: 'NoneType' object has no attribute 'split'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed

**Comment by pechaut78** [comment]
Ouch ouch ouch, this means I submitted the wrong file, thanks for telling me !
